import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar";
import Footer from "../components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    { name: "Accueil", href: "/" },
    {
      name: "À Propos",
      href: "/AboutUs",
      children: [
        { name: "Qui sommes-nous?", href: "/AboutUs#WhoUs" },
        { name: "Mission et valeurs", href: "/AboutUs#Mission" },
        { name: "Notre équipe", href: "/TeamMembers" },
      ],
    },
    {
      name: "Actualités",
      href: "/News",
    },
    { name: "Evénements", href: "/Events"},
    { name: "Boutique", href: "/Store" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar navItems={navItems} />
        {children}
        <Footer navItems={navItems} />
      </body>
    </html>
  );
}
